version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.7.1

jobs:
  test:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and run unit tests
          command: |
            docker build --pull -t gamestore:unittests -f ./GameStore.UnitTests/Dockerfile .
            docker run --name gamestore-tests gamestore:unittests
            docker cp gamestore-tests:/app/GameStore.UnitTests/TestResults ./
      - store_test_results:
          path: TestResults
  build-web:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: gamestore-web
          dockerfile: ./GameStore.WebUI/Dockerfile
      - gcp-gcr/push-image:
          image: gamestore-web
      - gcp-gcr/tag-image:
          image: gamestore-web
          source-tag: latest
          target-tag: << pipeline.git.revision >>
  build-advertisement-api:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: gamestore-advertisement-api
          dockerfile: ./GameStore.API.Advertisement/Dockerfile
      - gcp-gcr/push-image:
          image: gamestore-advertisement-api
      - gcp-gcr/tag-image:
          image: gamestore-advertisement-api
          source-tag: latest
          target-tag: << pipeline.git.revision >>

workflows:
  build:
    jobs:
      - test
      - build-web:
          requires:
            - test
      - build-advertisement-api:
          requires:
            - test
